FROM ubuntu:xenial
ENV container docker
ENV REPO=https://github.com/dchassin/gridlabd
ENV BRANCH=master
ENV ENABLE=gismo
ENV GET_WEATHER=no
ENV REMOVE_SOURCE=yes
ENV ENABLE_GDB=no
ENV LD_LIBRARY_PATH /usr/local/lib

VOLUME [ "/sys/fs/cgroup" ]
WORKDIR /tmp
COPY utilities/docker/ubuntu/*.sh /tmp/
RUN sudo chmod +wx *.sh
RUN sudo system.sh
RUN sudo gridlabd.sh
EXPOSE 6266-6299/tcp
